$(document).ready(function(){
	$(".card-text").click(function(){
		$(".drop-down-text").show();
		$(".card-text").hide();
		$("#list").slideToggle();
	});
	$(".drop-down-text").click(function(){
		$("#list").slideToggle();
		$(".drop-down-text").hide();
		$(".card-text").show();
	});
	$(".card-text2").click(function(){
		$(".drop-down-text2").show();
		$(".card-text2").hide();
		$("#list2").slideToggle();
	});
	$(".drop-down-text2").click(function(){
		$("#list2").slideToggle();
		$(".drop-down-text2").hide();
		$(".card-text2").show();
	});
	$(".card-text3").click(function(){
		$(".drop-down-text3").show();
		$(".card-text3").hide();
		$("#list3").slideToggle();
	});
	$(".drop-down-text3").click(function(){
		$("#list3").slideToggle();
		$(".drop-down-text3").hide();
		$(".card-text3").show();
	});
	$(".card-text4").click(function(){
		$(".drop-down-text4").show();
		$(".card-text4").hide();
		$("#list4").slideToggle();
	});
	$(".drop-down-text4").click(function(){
		$("#list4").slideToggle();
		$(".drop-down-text4").hide();
		$(".card-text4").show();
	});
	$(".card-text5").click(function(){
		$(".drop-down-text5").show();
		$(".card-text5").hide();
		$("#list5").slideToggle();
	});
	$(".drop-down-text5").click(function(){
		$("#list5").slideToggle();
		$(".drop-down-text5").hide();
		$(".card-text5").show();
	});
	$(".card-text6").click(function(){
		$(".drop-down-text6").show();
		$(".card-text6").hide();
		$("#list6").slideToggle();
	});
	$(".drop-down-text6").click(function(){
		$("#list6").slideToggle();
		$(".drop-down-text6").hide();
		$(".card-text6").show();
	});
   
});