$(document).ready(function(){
	$("#card-text1").click(function(){
		$("#drop-down1").show();
		$("#card-text1").hide();
		$("#list1").slideToggle();
	});
	$("#drop-down1").click(function(){
		$("#card-text1").show();
		$("#drop-down1").hide();
		$("#list1").slideToggle();
    });
    $("#card-text2").click(function(){
		$("#drop-down2").show();
		$("#card-text2").hide();
		$("#list2").slideToggle();
	});
	$("#drop-down2").click(function(){
		$("#card-text2").show();
		$("#drop-down2").hide();
		$("#list2").slideToggle();
    });
    $("#card-text3").click(function(){
		$("#drop-down3").show();
		$("#card-text3").hide();
		$("#list3").slideToggle();
	});
	$("#drop-down3").click(function(){
		$("#card-text3").show();
		$("#drop-down3").hide();
		$("#list3").slideToggle();
    });
    $("#card-text4").click(function(){
		$("#drop-down4").show();
		$("#card-text4").hide();
		$("#list4").slideToggle();
	});
	$("#drop-down4").click(function(){
		$("#card-text4").show();
		$("#drop-down4").hide();
		$("#list4").slideToggle();
    });
    $(".search-minimize").click(function(){
		$(".search-flex").show();
		$(".top-field-min").hide();
	});
   $(".close-icon").click(function(){
   	   $(".search-flex").hide();
   	   $(".top-field-min").show();
   });
});